/**
 * 获取当前默认版本
 */
export const FETCH_CLIENT_VERSION_REQUEST = "FETCH_CLIENT_VERSION_REQUEST";
export type FETCH_CLIENT_VERSION_REQUEST = typeof FETCH_CLIENT_VERSION_REQUEST;

/**
 * 获取网上版本
 */
export const FETCH_CLIENT_VERSION_REQUEST_INTERNET = "FETCH_CLIENT_VERSION_REQUEST_INTERNET";
export type FETCH_CLIENT_VERSION_REQUEST_INTERNET = typeof FETCH_CLIENT_VERSION_REQUEST_INTERNET;

